sonar.projectKey=go-toolkit
sonar.projectName=go-toolkit
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/*
sonar.go.coverage.reportPaths=coverage.out
sonar.links.ci=https://github.com/splitio/go-toolkit/actions
sonar.links.scm=https://github.com/splitio/go-toolkit
